import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './styles/globals.css'

import Navigation from '@/components/Navbar'
import Footer from '@/components/Footer'
import { AppProviders } from './providers' // ✅ wrap the theme

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Theme support for class-based dark mode */}
        <AppProviders>
          <Navigation />
            {children}
          <Footer />
        </AppProviders>
      </body>
    </html>
  )
}
